"""DDL del módulo de Finanzas/ERP contable — tablas con PK/FK `uuid`.

Generado desde los modelos ORM (que declaran String(36)) traduciendo
VARCHAR(36)->uuid, para ser compatible con el esquema de PRODUCCIÓN donde
empresa.id, empleado.id, etc. son uuid nativos. Se ejecuta en
_pre_create_migrations() (ANTES de create_all) para que las FK a tablas
uuid existentes no fallen. Idempotente: CREATE TABLE IF NOT EXISTS.
Orden FK-seguro (sorted_tables de SQLAlchemy).
"""
from sqlalchemy import text

FINANZAS_DDL = [
    """CREATE TABLE IF NOT EXISTS regimen_tributario_catalogo (
	id uuid NOT NULL, 
	codigo VARCHAR(20) NOT NULL, 
	nombre VARCHAR(120) NOT NULL, 
	tasa_igv NUMERIC(5, 2) NOT NULL, 
	tasa_renta_referencial NUMERIC(5, 2), 
	activo BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (codigo)
)""",
    """CREATE TABLE IF NOT EXISTS centro_costo (
	id uuid NOT NULL, 
	empresa_id uuid NOT NULL, 
	codigo VARCHAR(20) NOT NULL, 
	nombre VARCHAR(150) NOT NULL, 
	tipo_referencia VARCHAR(20) NOT NULL, 
	referencia_id uuid, 
	presupuesto_referencial NUMERIC(14, 2), 
	activo BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_centro_costo_empresa_codigo UNIQUE (empresa_id, codigo), 
	CONSTRAINT chk_centro_costo_tipo_referencia CHECK (tipo_referencia IN ('proyecto','area','empleado','libre')), 
	FOREIGN KEY(empresa_id) REFERENCES empresa (id)
)""",
    """CREATE TABLE IF NOT EXISTS cuenta_contable (
	id uuid NOT NULL, 
	empresa_id uuid NOT NULL, 
	codigo VARCHAR(20) NOT NULL, 
	nombre VARCHAR(200) NOT NULL, 
	tipo VARCHAR(20) NOT NULL, 
	naturaleza VARCHAR(20) NOT NULL, 
	nivel VARCHAR(20) NOT NULL, 
	cuenta_padre_id uuid, 
	activo BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cuenta_empresa_codigo UNIQUE (empresa_id, codigo), 
	CONSTRAINT chk_cuenta_tipo CHECK (tipo IN ('activo','pasivo','patrimonio','ingreso','gasto')), 
	CONSTRAINT chk_cuenta_naturaleza CHECK (naturaleza IN ('deudora','acreedora')), 
	CONSTRAINT chk_cuenta_nivel CHECK (nivel IN ('mayor','detalle')), 
	FOREIGN KEY(empresa_id) REFERENCES empresa (id), 
	FOREIGN KEY(cuenta_padre_id) REFERENCES cuenta_contable (id)
)""",
    """CREATE TABLE IF NOT EXISTS mapeo_transaccion_contable (
	id uuid NOT NULL, 
	empresa_id uuid NOT NULL, 
	tipo_evento VARCHAR(50) NOT NULL, 
	descripcion VARCHAR(255), 
	plantilla_lineas TEXT NOT NULL, 
	activo BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_mapeo_empresa_evento UNIQUE (empresa_id, tipo_evento), 
	FOREIGN KEY(empresa_id) REFERENCES empresa (id)
)""",
    """CREATE TABLE IF NOT EXISTS concepto_remunerativo (
	id uuid NOT NULL, 
	empresa_id uuid NOT NULL, 
	codigo VARCHAR(20) NOT NULL, 
	nombre VARCHAR(150) NOT NULL, 
	tipo VARCHAR(20) NOT NULL, 
	monto_referencial NUMERIC(14, 2), 
	formula_referencial VARCHAR(255), 
	cuenta_contable_id uuid, 
	activo VARCHAR(5) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_concepto_empresa_codigo UNIQUE (empresa_id, codigo), 
	CONSTRAINT chk_concepto_tipo CHECK (tipo IN ('ingreso','descuento','aporte_empleador')), 
	FOREIGN KEY(empresa_id) REFERENCES empresa (id), 
	FOREIGN KEY(cuenta_contable_id) REFERENCES cuenta_contable (id)
)""",
    """CREATE TABLE IF NOT EXISTS configuracion_tributaria_empresa (
	id uuid NOT NULL, 
	empresa_id uuid NOT NULL, 
	regimen_id uuid NOT NULL, 
	cuenta_igv_credito_fiscal_id uuid, 
	cuenta_igv_debito_fiscal_id uuid, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_config_tributaria_empresa UNIQUE (empresa_id), 
	FOREIGN KEY(empresa_id) REFERENCES empresa (id), 
	FOREIGN KEY(regimen_id) REFERENCES regimen_tributario_catalogo (id), 
	FOREIGN KEY(cuenta_igv_credito_fiscal_id) REFERENCES cuenta_contable (id), 
	FOREIGN KEY(cuenta_igv_debito_fiscal_id) REFERENCES cuenta_contable (id)
)""",
    """CREATE TABLE IF NOT EXISTS periodo_contable (
	id uuid NOT NULL, 
	empresa_id uuid NOT NULL, 
	anio INTEGER NOT NULL, 
	mes INTEGER NOT NULL, 
	estado VARCHAR(20) NOT NULL, 
	cerrado_por_id uuid, 
	cerrado_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_periodo_empresa_anio_mes UNIQUE (empresa_id, anio, mes), 
	CONSTRAINT chk_periodo_estado CHECK (estado IN ('abierto','cerrado')), 
	CONSTRAINT chk_periodo_mes CHECK (mes >= 1 AND mes <= 12), 
	FOREIGN KEY(empresa_id) REFERENCES empresa (id), 
	FOREIGN KEY(cerrado_por_id) REFERENCES empleado (id)
)""",
    """CREATE TABLE IF NOT EXISTS asiento_contable (
	id uuid NOT NULL, 
	empresa_id uuid NOT NULL, 
	numero VARCHAR(30) NOT NULL, 
	fecha DATE NOT NULL, 
	periodo_id uuid NOT NULL, 
	descripcion VARCHAR(500) NOT NULL, 
	origen VARCHAR(40) NOT NULL, 
	referencia_id uuid, 
	creado_por_id uuid, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_asiento_numero UNIQUE (empresa_id, periodo_id, numero), 
	FOREIGN KEY(empresa_id) REFERENCES empresa (id), 
	FOREIGN KEY(periodo_id) REFERENCES periodo_contable (id), 
	FOREIGN KEY(creado_por_id) REFERENCES empleado (id)
)""",
    """CREATE TABLE IF NOT EXISTS costo_promedio_material (
	id uuid NOT NULL, 
	empresa_id uuid NOT NULL, 
	material_id uuid NOT NULL, 
	almacen_id uuid NOT NULL, 
	cantidad_actual NUMERIC(18, 4) NOT NULL, 
	costo_promedio_actual NUMERIC(14, 4) NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_costo_promedio_mat_alm UNIQUE (empresa_id, material_id, almacen_id), 
	CONSTRAINT chk_costo_cantidad_no_negativa CHECK (cantidad_actual >= 0), 
	CONSTRAINT chk_costo_promedio_no_negativo CHECK (costo_promedio_actual >= 0), 
	FOREIGN KEY(empresa_id) REFERENCES empresa (id), 
	FOREIGN KEY(material_id) REFERENCES material (id), 
	FOREIGN KEY(almacen_id) REFERENCES almacen (id)
)""",
    """CREATE TABLE IF NOT EXISTS asiento_linea (
	id uuid NOT NULL, 
	asiento_id uuid NOT NULL, 
	cuenta_id uuid NOT NULL, 
	debito NUMERIC(14, 2) NOT NULL, 
	credito NUMERIC(14, 2) NOT NULL, 
	centro_costo_id uuid, 
	glosa VARCHAR(255), 
	PRIMARY KEY (id), 
	CONSTRAINT chk_linea_debito_xor_credito CHECK ((debito > 0 AND credito = 0) OR (credito > 0 AND debito = 0)), 
	FOREIGN KEY(asiento_id) REFERENCES asiento_contable (id), 
	FOREIGN KEY(cuenta_id) REFERENCES cuenta_contable (id), 
	FOREIGN KEY(centro_costo_id) REFERENCES centro_costo (id)
)""",
    """CREATE TABLE IF NOT EXISTS cobro_cliente (
	id uuid NOT NULL, 
	empresa_id uuid NOT NULL, 
	cliente_id uuid NOT NULL, 
	fecha_cobro DATE NOT NULL, 
	monto NUMERIC(14, 2) NOT NULL, 
	medio_pago VARCHAR(20) NOT NULL, 
	referencia VARCHAR(100), 
	asiento_id uuid, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT chk_cobro_medio CHECK (medio_pago IN ('efectivo','transferencia','cheque')), 
	CONSTRAINT chk_cobro_monto_positivo CHECK (monto > 0), 
	FOREIGN KEY(empresa_id) REFERENCES empresa (id), 
	FOREIGN KEY(cliente_id) REFERENCES cliente (id), 
	FOREIGN KEY(asiento_id) REFERENCES asiento_contable (id)
)""",
    """CREATE TABLE IF NOT EXISTS evento_contable_historial (
	id uuid NOT NULL, 
	empresa_id uuid NOT NULL, 
	tipo_evento VARCHAR(50) NOT NULL, 
	referencia_id uuid, 
	asiento_id uuid, 
	resultado VARCHAR(20) NOT NULL, 
	detalle TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(empresa_id) REFERENCES empresa (id), 
	FOREIGN KEY(asiento_id) REFERENCES asiento_contable (id)
)""",
    """CREATE TABLE IF NOT EXISTS factura_cliente (
	id uuid NOT NULL, 
	empresa_id uuid NOT NULL, 
	cliente_id uuid NOT NULL, 
	proyecto_id uuid, 
	numero_documento VARCHAR(50) NOT NULL, 
	tipo_documento VARCHAR(20) NOT NULL, 
	fecha_emision DATE NOT NULL, 
	fecha_vencimiento DATE, 
	moneda VARCHAR(3) NOT NULL, 
	subtotal NUMERIC(14, 2) NOT NULL, 
	igv NUMERIC(14, 2) NOT NULL, 
	total NUMERIC(14, 2) NOT NULL, 
	estado VARCHAR(20) NOT NULL, 
	asiento_id uuid, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_factura_cli_doc UNIQUE (empresa_id, tipo_documento, numero_documento), 
	CONSTRAINT chk_factura_cli_tipo_documento CHECK (tipo_documento IN ('factura','boleta','nota_credito','nota_debito')), 
	CONSTRAINT chk_factura_cli_estado CHECK (estado IN ('pendiente','cobrada_parcial','cobrada','anulada')), 
	CONSTRAINT chk_factura_cli_montos_no_negativos CHECK (subtotal >= 0 AND igv >= 0 AND total >= 0), 
	FOREIGN KEY(empresa_id) REFERENCES empresa (id), 
	FOREIGN KEY(cliente_id) REFERENCES cliente (id), 
	FOREIGN KEY(proyecto_id) REFERENCES proyecto (id), 
	FOREIGN KEY(asiento_id) REFERENCES asiento_contable (id)
)""",
    """CREATE TABLE IF NOT EXISTS pago_proveedor (
	id uuid NOT NULL, 
	empresa_id uuid NOT NULL, 
	proveedor_id uuid NOT NULL, 
	fecha_pago DATE NOT NULL, 
	monto NUMERIC(14, 2) NOT NULL, 
	medio_pago VARCHAR(20) NOT NULL, 
	referencia VARCHAR(100), 
	asiento_id uuid, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT chk_pago_medio CHECK (medio_pago IN ('efectivo','transferencia','cheque')), 
	CONSTRAINT chk_pago_monto_positivo CHECK (monto > 0), 
	FOREIGN KEY(empresa_id) REFERENCES empresa (id), 
	FOREIGN KEY(proveedor_id) REFERENCES proveedor (id), 
	FOREIGN KEY(asiento_id) REFERENCES asiento_contable (id)
)""",
    """CREATE TABLE IF NOT EXISTS planilla (
	id uuid NOT NULL, 
	empresa_id uuid NOT NULL, 
	periodo_id uuid NOT NULL, 
	fecha_proceso DATE NOT NULL, 
	estado VARCHAR(20) NOT NULL, 
	total_ingresos NUMERIC(14, 2) NOT NULL, 
	total_descuentos NUMERIC(14, 2) NOT NULL, 
	total_aportes NUMERIC(14, 2) NOT NULL, 
	total_neto NUMERIC(14, 2) NOT NULL, 
	asiento_provision_id uuid, 
	asiento_pago_id uuid, 
	aprobado_por_id uuid, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_planilla_empresa_periodo UNIQUE (empresa_id, periodo_id), 
	CONSTRAINT chk_planilla_estado CHECK (estado IN ('borrador','calculada','aprobada','pagada','anulada')), 
	FOREIGN KEY(empresa_id) REFERENCES empresa (id), 
	FOREIGN KEY(periodo_id) REFERENCES periodo_contable (id), 
	FOREIGN KEY(asiento_provision_id) REFERENCES asiento_contable (id), 
	FOREIGN KEY(asiento_pago_id) REFERENCES asiento_contable (id), 
	FOREIGN KEY(aprobado_por_id) REFERENCES empleado (id)
)""",
    """CREATE TABLE IF NOT EXISTS activo_fijo (
	id uuid NOT NULL, 
	empresa_id uuid NOT NULL, 
	equipo_id uuid, 
	nombre VARCHAR(200) NOT NULL, 
	fecha_adquisicion DATE NOT NULL, 
	valor_adquisicion NUMERIC(14, 2) NOT NULL, 
	valor_residual NUMERIC(14, 2) NOT NULL, 
	vida_util_meses INTEGER NOT NULL, 
	metodo_depreciacion VARCHAR(20) NOT NULL, 
	fecha_inicio_depreciacion DATE NOT NULL, 
	estado VARCHAR(20) NOT NULL, 
	centro_costo_id uuid, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT chk_activo_metodo CHECK (metodo_depreciacion IN ('linea_recta')), 
	CONSTRAINT chk_activo_estado CHECK (estado IN ('activo','depreciado_total','dado_de_baja')), 
	CONSTRAINT chk_activo_vida_util CHECK (vida_util_meses > 0), 
	CONSTRAINT chk_activo_valores CHECK (valor_adquisicion >= 0 AND valor_residual >= 0), 
	FOREIGN KEY(empresa_id) REFERENCES empresa (id), 
	FOREIGN KEY(equipo_id) REFERENCES equipo (id), 
	FOREIGN KEY(centro_costo_id) REFERENCES centro_costo (id)
)""",
    """CREATE TABLE IF NOT EXISTS aplicacion_cobro_cliente (
	id uuid NOT NULL, 
	cobro_id uuid NOT NULL, 
	factura_id uuid NOT NULL, 
	monto_aplicado NUMERIC(14, 2) NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT chk_aplicacion_cobro_monto_positivo CHECK (monto_aplicado > 0), 
	FOREIGN KEY(cobro_id) REFERENCES cobro_cliente (id), 
	FOREIGN KEY(factura_id) REFERENCES factura_cliente (id)
)""",
    """CREATE TABLE IF NOT EXISTS boleta_pago (
	id uuid NOT NULL, 
	planilla_id uuid NOT NULL, 
	empleado_id uuid NOT NULL, 
	total_ingresos NUMERIC(14, 2) NOT NULL, 
	total_descuentos NUMERIC(14, 2) NOT NULL, 
	total_aportes NUMERIC(14, 2) NOT NULL, 
	total_neto NUMERIC(14, 2) NOT NULL, 
	pdf_url TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(planilla_id) REFERENCES planilla (id), 
	FOREIGN KEY(empleado_id) REFERENCES empleado (id)
)""",
    """CREATE TABLE IF NOT EXISTS boleta_pago_detalle (
	id uuid NOT NULL, 
	boleta_id uuid NOT NULL, 
	concepto_id uuid NOT NULL, 
	monto NUMERIC(14, 2) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(boleta_id) REFERENCES boleta_pago (id), 
	FOREIGN KEY(concepto_id) REFERENCES concepto_remunerativo (id)
)""",
    """CREATE TABLE IF NOT EXISTS depreciacion_mensual (
	id uuid NOT NULL, 
	activo_fijo_id uuid NOT NULL, 
	periodo_id uuid NOT NULL, 
	monto_depreciado NUMERIC(14, 2) NOT NULL, 
	valor_en_libros_resultante NUMERIC(14, 2) NOT NULL, 
	asiento_id uuid, 
	procesado_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_depreciacion_activo_periodo UNIQUE (activo_fijo_id, periodo_id), 
	FOREIGN KEY(activo_fijo_id) REFERENCES activo_fijo (id), 
	FOREIGN KEY(periodo_id) REFERENCES periodo_contable (id), 
	FOREIGN KEY(asiento_id) REFERENCES asiento_contable (id)
)""",
    """CREATE TABLE IF NOT EXISTS factura_proveedor (
	id uuid NOT NULL, 
	empresa_id uuid NOT NULL, 
	proveedor_id uuid NOT NULL, 
	orden_compra_id uuid, 
	numero_documento VARCHAR(50) NOT NULL, 
	tipo_documento VARCHAR(20) NOT NULL, 
	fecha_emision DATE NOT NULL, 
	fecha_vencimiento DATE NOT NULL, 
	moneda VARCHAR(3) NOT NULL, 
	subtotal NUMERIC(14, 2) NOT NULL, 
	igv NUMERIC(14, 2) NOT NULL, 
	total NUMERIC(14, 2) NOT NULL, 
	estado VARCHAR(20) NOT NULL, 
	asiento_id uuid, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_factura_prov_doc UNIQUE (empresa_id, proveedor_id, numero_documento), 
	CONSTRAINT chk_factura_tipo_documento CHECK (tipo_documento IN ('factura','boleta','nota_credito','nota_debito')), 
	CONSTRAINT chk_factura_estado CHECK (estado IN ('pendiente','pagada_parcial','pagada','anulada')), 
	CONSTRAINT chk_factura_montos_no_negativos CHECK (subtotal >= 0 AND igv >= 0 AND total >= 0), 
	FOREIGN KEY(empresa_id) REFERENCES empresa (id), 
	FOREIGN KEY(proveedor_id) REFERENCES proveedor (id), 
	FOREIGN KEY(orden_compra_id) REFERENCES orden_compra (id), 
	FOREIGN KEY(asiento_id) REFERENCES asiento_contable (id)
)""",
    """CREATE TABLE IF NOT EXISTS aplicacion_pago_proveedor (
	id uuid NOT NULL, 
	pago_id uuid NOT NULL, 
	factura_id uuid NOT NULL, 
	monto_aplicado NUMERIC(14, 2) NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT chk_aplicacion_monto_positivo CHECK (monto_aplicado > 0), 
	FOREIGN KEY(pago_id) REFERENCES pago_proveedor (id), 
	FOREIGN KEY(factura_id) REFERENCES factura_proveedor (id)
)""",
]


def crear_tablas_finanzas(conn) -> None:
    """Crea las tablas del módulo de finanzas con tipos uuid (idempotente)."""
    for ddl in FINANZAS_DDL:
        conn.execute(text(ddl))
